
stages:
  - test
  - build
  - e2e
  - deploy

test:jest:
 image: node:10.16.3
 stage: test
 cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
     - node_modules/
     - .jest/cache/
 script:
   - yarn install
   - yarn test

build:android:
  image: circleci/android:api-28-node
  stage: build
  before_script:
    - sudo sysctl fs.inotify.max_user_watches=524288
    - sudo sysctl -p
  script:
    - yarn install
    - cd android
    - bundle install
    - fastlane assemble_build
    - cp app/build/outputs/apk/release/app-release.apk ../Minds-$CI_BUILD_REF_SLUG.apk
  artifacts:
    name: "Minds APK"
    paths:
      - Minds-$CI_BUILD_REF_SLUG.apk
    expire_in: 7 days
    when: on_success

deploy:s3:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
    - aws s3 cp Minds-$CI_BUILD_REF_SLUG.apk s3://minds-repo/mobile/Minds-$CI_BUILD_REF_SLUG.apk
  dependencies:
   - build:android
  only:
    refs:
      - /^release-*/
      - /^test-*/

deploy:google_play:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
  dependencies:
    - build:android
  only:
    refs:
      - /^stable-*/
      - /^test-*/
