
stages:
  - build
  - e2e
  - i18n
  - deploy
  - test

test:jest:
  image: node:10.16.3
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .jest/cache/
  before_script:
    - yarn install
  script:
    - yarn test

i18n:upload:
  image: node:10.16.3
  stage: i18n
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn locale upload --poeditor-key=${CI_POEDITOR_KEY} --overwrite=1
  only:
    refs:
      - /^release-*/

i18n:uploadsync:
  image: node:10.16.3
  stage: i18n
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn locale upload --poeditor-key=${CI_POEDITOR_KEY} --overwrite=1 --sync_terms=1
  only:
    refs:
      - master

build:android:
  image: circleci/android:api-28-node
  stage: build
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
      - android/vendor/bundle
      - .gradle/caches
      - .gradle/wrapper
      - .android/build-cache/
  before_script:
    - 'sed -i ''s/^apply from: "..\/..\/node_modules\/\@sentry\/react-native\/sentry.gradle"//'' android/app/build.gradle'
    - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
    - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradle"
    - sudo sysctl fs.inotify.max_user_watches=524288
    - sudo sysctl -p
    - yarn install
    - cd android
    - bundle install --path=vendor/bundle
  script:
    - bundle exec fastlane assemble_build
    - mv app/build/outputs/apk/release/app-release.apk ../Minds-$CI_BUILD_REF_SLUG.apk
  artifacts:
    name: "Minds APK"
    paths:
      - Minds-$CI_BUILD_REF_SLUG.apk
    expire_in: 7 days
    when: on_success

# build:android-playstore:
#   image: circleci/android:api-28-node
#   stage: build
#   before_script:
#     - sudo sysctl fs.inotify.max_user_watches=524288
#     - sudo sysctl -p
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - node_modules/
#   script:
#     - yarn install
#     - cd android
#     - bundle install
#     - fastlane assemble_build
#     - cp app/build/outputs/apk/release/app-release.apk ../Minds-$CI_BUILD_REF_SLUG.apk
#   artifacts:
#     name: "Minds APK"
#     paths:
#       - Minds-$CI_BUILD_REF_SLUG.apk
#     expire_in: 7 days
#     when: on_success

deploy:s3:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
    - aws s3 cp Minds-$CI_BUILD_REF_SLUG.apk s3://minds-repo/mobile/Minds-$CI_BUILD_REF_SLUG.apk
  dependencies:
   - build:android
  only:
    refs:
      - /^stable-*/
      - /^test-*/

deploy:google_play:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
  dependencies:
    - build:android
  only:
    refs:
      - /^stable-*/
      - /^test-*/
