
stages:
  - test
  - build
  - e2e
  - deploy

test:jest:
 image: node:10.16.3
 stage: test
 cache:
   key: ${CI_COMMIT_REF_SLUG}
   paths:
     - node_modules/
     - .jest/cache/
 script:
   - yarn install
   - yarn test

build:android:
  image: circleci/android:api-28-node@sha256:92ffee5a1d98d856634e8b71132e8a95d96c83a63fde1099be3d86df3106def9
  stage: build
  before_script:
    - sudo sysctl fs.inotify.max_user_watches=524288
    - sudo sysctl -p
  script:
    - yarn install
    - cd android
    - bundle install
    - fastlane assemble_build
    - cp app/build/outputs/apk/release/app-release.apk ../Minds-$CI_BUILD_REF_SLUG.apk
  artifacts:
    name: "Minds APK"
    paths:
      - Minds-$CI_BUILD_REF_SLUG.apk
    expire_in: 7 days
    when: on_success

e2e:browserstacks:
  image: node:10.16.3
  stage: e2e
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - yarn install
    - export bsAPP=`curl -u "${bsUSER}:${bsKEY}" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@./Minds-$CI_BUILD_REF_SLUG.apk"| grep -o 'bs\:\/\/.*"' | sed 's/.$//'`
    - yarn e2e
  tags:
    - docker
  dependencies:
   - build:android
  only:
    refs:
      - /^stable-*/
      - /^release-*/
      - /^feat-*/
      - /^test-*/
  allow_failure: true

deploy:s3:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
    - aws s3 cp Minds-$CI_BUILD_REF_SLUG.apk s3://minds-repo/mobile/Minds-$CI_BUILD_REF_SLUG.apk
  dependencies:
   - build:android
  only:
    refs:
      - /^release-*/
      - /^test-*/

deploy:google_play:
  image: minds/ci:latest
  stage: deploy
  script:
    - echo "Upload Minds-$CI_BUILD_REF_SLUG.apk"
  dependencies:
    - build:android
  only:
    refs:
      - /^stable-*/
      - /^test-*/
